### ISSUE TITLE
Suggestions after testing

### ISSUE THREAD

**Issue by Bazireinvesting** [aergoio/wallet-extension#13]
Hey guys, 

here are my impressions on your wallet. Navigating through it is smooth and easy but 2 details caught my attention. 

1) Something I regret on Metamask too: When I'm on the main menu (DEPOSIT) with my QR Code, I'm 3 clicks away from viewing my account on AergoScan and this is not the best when transferring tokens or using DApps. My unique account icon in the top left corner would be the perfect place to integrate the AergoScan link imo

2) I don't see any Copy/Paste function for the wallet adress, I suppose you're going to integrate it soon

**Comment by graup** [comment]
Hi @Bazireinvesting, thanks for your suggestions. We'll work on both of those soon.

**Comment by Bazireinvesting** [comment]
My pleasure, good luck you're doing wonders! The auto-lock is also annoying but you know already

**Comment by graup** [comment]
Improved in Aergo Connect 2.0
https://github.com/aergoio/aergo-connect
